server:
  port: 8089

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: soasong
          uri: lb://SOASONG
          predicates:
            - Path=/songs/**

        - id: user
          uri: lb://USERS-MICROSERVICE
          predicates:
            - Path=/users/**

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
